### ISSUE TITLE
add cascade api support

### ISSUE THREAD

**Issue by ThinkontrolSY** [terassyi/go-softether-api#2]
## New supported API

CreateLink - Create New Cascade Connection
GetLink - Get the Cascade Connection Setting
SetLink - Change Existing Cascade Connection
EnumLink - Get List of Cascade Connections
SetLinkOnline - Switch Cascade Connection to Online Status
SetLinkOffline - Switch Cascade Connection to Offline Status
DeleteLink - Delete Cascade Connection Setting
RenameLink - Change Name of Cascade Connection
GetLinkStatus - Get Current Cascade Connection Status

**Comment by terassyi** [comment]
Thank you for adding new api supports.
After checking codes, if there is no problems I'll merge it.
